// RoboMeet Bridge service worker.
// Connects to the local RoboMeet app over WebSocket and, on its request, opens and drives Meet windows.
// It only ever touches tabs it created itself (registry kept in chrome.storage.session).
importScripts('config.js'); // defines self.ROBOMEET_BRIDGE = { ports: [...], secret: '...' } (generated by bin/bridge-build.mjs)

const sockets = new Map(); // port -> WebSocket
const connecting = new Set();

async function registry() { return (await chrome.storage.session.get('tabs')).tabs || {}; }
async function saveRegistry(tabs) { await chrome.storage.session.set({ tabs }); }

function connect() {
  for (const port of self.ROBOMEET_BRIDGE.ports) {
    const open = sockets.get(port);
    if ((open && open.readyState <= 1) || connecting.has(port)) continue;
    connecting.add(port);
    let socket;
    try { socket = new WebSocket(`ws://127.0.0.1:${port}/bridge`); } catch { connecting.delete(port); continue; }
    socket.onopen = () => {
      connecting.delete(port);
      sockets.set(port, socket);
      socket.send(JSON.stringify({ type: 'hello', secret: self.ROBOMEET_BRIDGE.secret, version: chrome.runtime.getManifest().version }));
    };
    socket.onmessage = event => { void handle(port, socket, event.data); };
    socket.onclose = () => { connecting.delete(port); if (sockets.get(port) === socket) sockets.delete(port); };
    socket.onerror = () => {};
  }
}

const send = (socket, message) => { if (socket.readyState === 1) socket.send(JSON.stringify(message)); };

async function handle(port, socket, raw) {
  let message;
  try { message = JSON.parse(raw); } catch { return; }
  if (message.type === 'ping') return send(socket, { type: 'pong' });
  if (!message.id || !methods[message.method]) return send(socket, { id: message.id, error: 'Unknown bridge method' });
  try { send(socket, { id: message.id, result: await methods[message.method](message.params || {}, port) }); }
  catch (error) { send(socket, { id: message.id, error: String(error?.message || error) }); }
}

const methods = {
  async open({ url, role, nonce, muted = false, bounds = {} }, port) {
    const target = new URL(url);
    if (target.protocol !== 'https:' || target.hostname !== 'meet.google.com') throw new Error('RoboMeet Bridge only opens Google Meet URLs.');
    if (!['robot', 'observer'].includes(role) || !/^[a-f0-9]{8,64}$/.test(nonce)) throw new Error('Invalid role or nonce.');
    target.hash = `robomeet-${role}=${nonce}`;
    const window = await chrome.windows.create({ url: target.href, focused: false, type: 'normal', ...bounds });
    const tab = window.tabs[0];
    const tabs = await registry();
    tabs[tab.id] = { role, nonce, windowId: window.id, port };
    await saveRegistry(tabs);
    if (muted) await chrome.tabs.update(tab.id, { muted: true });
    return { tabId: tab.id, windowId: window.id };
  },
  async call({ tabId, fn, args = [] }) {
    const tabs = await registry();
    if (!tabs[tabId]) throw new Error('RoboMeet Bridge does not own that tab.');
    const [injection] = await chrome.scripting.executeScript({
      target: { tabId, frameIds: [0] },
      world: 'MAIN',
      args: [fn, args],
      func: async (name, parameters) => {
        const agent = window.__robomeetAgent;
        if (!agent) return { missing: true };
        if (typeof agent[name] !== 'function') return { error: `Unknown agent method ${name}` };
        try { return { value: await agent[name](...parameters) }; }
        catch (error) { return { error: String(error?.message || error) }; }
      },
    });
    return injection?.result ?? { missing: true };
  },
  // Real input via the debugger protocol, attached only for the duration of these actions. Real input gives
  // the page user activation (Chrome requires it before Web Audio starts) and makes Meet's Join click genuine.
  // actions: [{ kind: 'click', x, y } | { kind: 'key', key: 'F13' } | { kind: 'text', text }]
  async input({ tabId, actions = [] }) {
    const tabs = await registry();
    if (!tabs[tabId]) throw new Error('RoboMeet Bridge does not own that tab.');
    if (!Array.isArray(actions) || actions.length > 10) throw new Error('Invalid input actions.');
    const keys = { F13: 124 };
    for (const action of actions) {
      if (action.kind === 'click' && ![action.x, action.y].every(value => Number.isFinite(value) && value >= 0 && value < 10_000)) throw new Error('Invalid click point.');
      if (action.kind === 'key' && !keys[action.key]) throw new Error('Unsupported key.');
      if (action.kind === 'text' && (typeof action.text !== 'string' || action.text.length > 80)) throw new Error('Invalid text.');
      if (!['click', 'key', 'text'].includes(action.kind)) throw new Error('Unknown input action.');
    }
    const target = { tabId };
    const send = (method, params) => chrome.debugger.sendCommand(target, method, params);
    await chrome.debugger.attach(target, '1.3');
    try {
      for (const action of actions) {
        if (action.kind === 'click') {
          const mouse = (type, extra = {}) => send('Input.dispatchMouseEvent', { type, x: action.x, y: action.y, button: 'left', buttons: type === 'mousePressed' ? 1 : 0, clickCount: 1, ...extra });
          await mouse('mouseMoved', { button: 'none', clickCount: 0 });
          await mouse('mousePressed');
          await mouse('mouseReleased');
        } else if (action.kind === 'key') {
          const code = keys[action.key];
          await send('Input.dispatchKeyEvent', { type: 'rawKeyDown', key: action.key, code: action.key, windowsVirtualKeyCode: code, nativeVirtualKeyCode: code });
          await send('Input.dispatchKeyEvent', { type: 'keyUp', key: action.key, code: action.key, windowsVirtualKeyCode: code, nativeVirtualKeyCode: code });
        } else {
          await send('Input.insertText', { text: action.text });
        }
      }
    } finally {
      await chrome.debugger.detach(target).catch(() => {});
    }
    return true;
  },
  async close({ tabId }) {
    const tabs = await registry();
    const entry = tabs[tabId];
    if (!entry) return false;
    delete tabs[tabId];
    await saveRegistry(tabs);
    await chrome.windows.remove(entry.windowId).catch(() => {});
    return true;
  },
};

chrome.tabs.onRemoved.addListener(async tabId => {
  const tabs = await registry();
  const entry = tabs[tabId];
  if (!entry) return;
  delete tabs[tabId];
  await saveRegistry(tabs);
  const socket = sockets.get(entry.port);
  if (socket) send(socket, { type: 'event', event: 'tab-closed', tabId });
});

chrome.runtime.onStartup.addListener(connect);
chrome.runtime.onInstalled.addListener(connect);
chrome.alarms.create('robomeet-connect', { periodInMinutes: 0.5 });
chrome.alarms.onAlarm.addListener(connect);
connect();
